/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import java.awt.event.ActionListener;
import controller.LoginController;
import dao.UserDao;
import javax.swing.JOptionPane;
import model.User;


/**
 *
 * @author NITRO V 15
 */
public class Signup extends javax.swing.JFrame {
    UserDao userDao = new UserDao();

    /**
     * Creates new form SignUp
     */
    public Signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        S_username = new javax.swing.JTextField();
        S_email = new javax.swing.JTextField();
        S_SignupBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        S_LoginBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        S_passwordF1 = new javax.swing.JPasswordField();
        Security_question = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        S_SecurityAnswer = new javax.swing.JTextField();
        showPassword = new javax.swing.JCheckBox();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(239, 239, 239));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("SignUp");

        jLabel3.setText("Username");

        jLabel4.setText("Email");

        jLabel5.setText("Password");

        S_username.setBackground(new java.awt.Color(217, 217, 217));
        S_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                S_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                S_usernameFocusLost(evt);
            }
        });
        S_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S_usernameActionPerformed(evt);
            }
        });

        S_email.setBackground(new java.awt.Color(217, 217, 217));
        S_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                S_emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                S_emailFocusLost(evt);
            }
        });
        S_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S_emailActionPerformed(evt);
            }
        });

        S_SignupBtn.setBackground(new java.awt.Color(44, 132, 231));
        S_SignupBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        S_SignupBtn.setForeground(new java.awt.Color(255, 255, 255));
        S_SignupBtn.setText("SignUp");
        S_SignupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S_SignupBtnActionPerformed(evt);
            }
        });

        jLabel7.setText("Already have an account?");

        S_LoginBtn.setBackground(new java.awt.Color(204, 204, 204));
        S_LoginBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        S_LoginBtn.setForeground(new java.awt.Color(51, 51, 51));
        S_LoginBtn.setText("Login");
        S_LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S_LoginBtnActionPerformed(evt);
            }
        });

        jLabel8.setText("One stop solution for all electronics");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Electrobyte");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Electrobyte (Custom) (Custom) (1).png"))); // NOI18N

        S_passwordF1.setBackground(new java.awt.Color(217, 217, 217));
        S_passwordF1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                S_passwordF1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                S_passwordF1FocusLost(evt);
            }
        });

        Security_question.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What's your Favrouite Petname?", "What's Your Nickname?", "What's Your LuckyNumber(In words)?" }));
        Security_question.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Security_questionActionPerformed(evt);
            }
        });

        jLabel6.setText("Security Question");

        S_SecurityAnswer.setBackground(new java.awt.Color(217, 217, 217));
        S_SecurityAnswer.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                S_SecurityAnswerFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                S_SecurityAnswerFocusLost(evt);
            }
        });
        S_SecurityAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S_SecurityAnswerActionPerformed(evt);
            }
        });

        showPassword.setText("Show Password");
        showPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)))
                    .addComponent(S_SecurityAnswer, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Security_question, javax.swing.GroupLayout.Alignment.LEADING, 0, 281, Short.MAX_VALUE)
                    .addComponent(S_passwordF1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(S_email, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(S_username, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(showPassword)))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(S_LoginBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(145, 145, 145))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(S_SignupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(127, 127, 127))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(S_username, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(S_email, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(S_passwordF1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Security_question, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(S_SecurityAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(S_SignupBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(S_LoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(346, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void S_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_S_usernameActionPerformed

    private void S_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_S_emailActionPerformed

    private void S_SignupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S_SignupBtnActionPerformed

        
    }//GEN-LAST:event_S_SignupBtnActionPerformed

    private void S_LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S_LoginBtnActionPerformed
        Login login = new Login();
        LoginController logincontroller = new LoginController(login);
        logincontroller.open();
        login.setVisible(true);
        login.setLocationRelativeTo(null); //bicha ma basne ho yeleeeeeee
        this.dispose(); // Close the signup window
    }//GEN-LAST:event_S_LoginBtnActionPerformed

    private void S_SecurityAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S_SecurityAnswerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_S_SecurityAnswerActionPerformed

    private void Security_questionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Security_questionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Security_questionActionPerformed

    private void showPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordActionPerformed
        // TODO add your handling code here:
            if(showPassword.isSelected()){
                S_passwordF1.setEchoChar((char)0);
            }else{
                S_passwordF1.setEchoChar('*');
            }
    }//GEN-LAST:event_showPasswordActionPerformed

    private void S_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_S_usernameFocusGained
        // TODO add your handling code here:
        if (S_username.getText().equals("Username")) {
            S_username.setText("");
        }
    }//GEN-LAST:event_S_usernameFocusGained

    private void S_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_S_usernameFocusLost
        // TODO add your handling code here:
        if (S_username.getText().isEmpty()) {
            S_username.setText("Username");
        }
    }//GEN-LAST:event_S_usernameFocusLost

    private void S_emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_S_emailFocusGained
        // TODO add your handling code here:
        if (S_email.getText().equals("Email")) {
            S_email.setText("");
        }
    }//GEN-LAST:event_S_emailFocusGained

    private void S_emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_S_emailFocusLost
        // TODO add your handling code here:
        if (S_email.getText().isEmpty()) {
            S_email.setText("Email");
        }
    }//GEN-LAST:event_S_emailFocusLost

    private void S_passwordF1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_S_passwordF1FocusGained
        // TODO add your handling code here:
        if (String.valueOf(S_passwordF1.getPassword()).equals("Password")) {
            S_passwordF1.setText("");
            S_passwordF1.setEchoChar('*');
        }
    }//GEN-LAST:event_S_passwordF1FocusGained

    private void S_passwordF1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_S_passwordF1FocusLost
        // TODO add your handling code here:
        if (String.valueOf(S_passwordF1.getPassword()).isEmpty()) {
            S_passwordF1.setText("Password");
            S_passwordF1.setEchoChar((char)0);
        }
    }//GEN-LAST:event_S_passwordF1FocusLost

    private void S_SecurityAnswerFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_S_SecurityAnswerFocusGained
        // TODO add your handling code here:
        if (S_SecurityAnswer.getText().equals("Answer")) {
            S_SecurityAnswer.setText("");
        }
    }//GEN-LAST:event_S_SecurityAnswerFocusGained

    private void S_SecurityAnswerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_S_SecurityAnswerFocusLost
        // TODO add your handling code here:
        if (S_SecurityAnswer.getText().isEmpty()) {
            S_SecurityAnswer.setText("Answer");
        }
    }//GEN-LAST:event_S_SecurityAnswerFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton S_LoginBtn;
    private javax.swing.JTextField S_SecurityAnswer;
    private javax.swing.JButton S_SignupBtn;
    private javax.swing.JTextField S_email;
    private javax.swing.JPasswordField S_passwordF1;
    private javax.swing.JTextField S_username;
    private javax.swing.JComboBox<String> Security_question;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JCheckBox showPassword;
    // End of variables declaration//GEN-END:variables

    public void addAddUserListener(ActionListener listener) {
        S_SignupBtn.addActionListener(listener);
    }
    public javax.swing.JTextField getEmailField() {
        return S_email;
    }
    
    public javax.swing.JPasswordField getPasswordField() {
        return S_passwordF1;
    }
    public javax.swing.JTextField getUsernameField() {
        return S_username;
    }
    public javax.swing.JTextField getSecurity_AnsField() {
        return S_SecurityAnswer;
    }
    public javax.swing.JComboBox getSecurityQuestion(){
        return Security_question;
    }
    
}
